### ISSUE TITLE
[App - Course] As a waste picker, I want to be able to finish the exercise

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#262] opened 2024-09-14 17:48 UTC
Description:
An error closes a question and completes the course, you do not receive points but automatically generates the certificate

Solution Proposal:
Add animation that successfully completes the exercise to then notify the completion of the course if it is the last step

Bug Priority Number: 1

Comments:
Description for reproducibility would be helpful for devs

**Comment by madsWesth** [comment] 2024-09-21 13:39
This issue seems to be out of date as we haven't been able replicate/reproduce the issue.

Reproduction attempts:
- Answer wrongfully on a question. In case *error* referred to an incorrect answer.
- Programmatically induce a technical error in the answer submission process. In case *error* referred to a technical error.
None of these resulted in the question closing or the course completing.

A completion animation is played at the end of a course even if the answers to the exercises are wrong and 0 points is awarded to the user but isn't this the desired behavior?

**Comment by LucaPurcilly** [comment] 2024-10-14 12:41
![Image](https://github.com/user-attachments/assets/13f91a8f-e28e-46f2-9f66-c425d0798ee9)
Points are now correctly awarded on final click.

**Closed** 2024-11-07 10:04 UTC
